### ISSUE TITLE
* (ArgumentError) unknown application: :bakeware

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [bake-bake-bake/bakeware#136]
When trying to execute `mix release` on a Windows 11 machine for a Phoenix project I get the following error:

```
* assembling market_manager-2.1.5 on MIX_ENV=prod
* using config/runtime.exs to configure the release at runtime
←[32m* assembling←[39m bakeware market_manager

** (ArgumentError) unknown application: :bakeware
    (elixir 1.15.4) lib/application.ex:1010: Application.app_dir/1
    (elixir 1.15.4) lib/application.ex:1041: Application.app_dir/2
    (bakeware 0.2.4) lib/bakeware/assembler.ex:71: Bakeware.Assembler.create_paths/1
    (bakeware 0.2.4) lib/bakeware/assembler.ex:83: Bakeware.Assembler.do_assemble/1
    (bakeware 0.2.4) lib/bakeware/assembler.ex:37: Bakeware.Assembler.assemble/1
    (mix 1.15.4) lib/mix/tasks/release.ex:1064: Mix.Tasks.Release.run_steps/1
    (mix 1.15.4) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.4) lib/mix/cli.ex:92: Mix.CLI.run_task/2
```

I am using PowerShell with Admin privileges and I have set the following env variables:

```
$env:CC="gcc"
$env:MAKE="make"
$env:MIX_ENV="prod"
``` 

I have installed all the dependencies via choco with `choco install -y zstandard make mingw`. 

Further, here are my system settings:

```
Edition	Windows 11 Home
Version	22H2
OS build	22621.2283
Experience	Windows Feature Experience Pack 1000.22662.1000.0
```

Why cant I make bakeware work?

**Comment by fhunleth** [comment]
Could you give https://github.com/burrito-elixir/burrito a try? It's the successor to Bakeware and the author is actively maintaining it.

**Comment by Fl4m3Ph03n1x** [comment]
Gave it a shot, didn't work well:
https://github.com/burrito-elixir/burrito/issues/111

This was for a hello world phoenix app. Have not tried with Umbrella apps, they usually generate more issues.
