### ISSUE TITLE
generating coveralls reports requires BAKEWARE_ARGC to be set

### ISSUE THREAD

**Issue by EdBondRSA** [bake-bake-bake/bakeware#44]
```
==> scanado_worker
Cover compiling modules ...
warning: Caught exception in main/1: :error => :function_clause
  (elixir 1.10.3) lib/integer.ex:232: Integer.parse(nil, 10)
  (scanado_worker 0.1.0) lib/bakeware/script.ex:35: ScanadoWorker._main/0
  (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
  (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

there isn't a default value set if it isn't there and during a 

```
mix coveralls.html
```

it requires the setup of this argument to continue

IE:

```
export BAKEWARE_ARGC=0
```

**Comment by fhunleth** [comment]
Fixed in #66.
