### ISSUE TITLE
Running the SimpleScript example fails

### ISSUE THREAD

**Issue by suprafly** [bake-bake-bake/bakeware#60]
```
20:25:45.781 [error] Task #PID<0.628.0> started from SimpleScript.Supervisor terminating
** (UndefinedFunctionError) function Bakeware.Script._main/1 is undefined (module Bakeware.Script is not available)
    Bakeware.Script._main(#Function<0.13039694/1 in SimpleScript."-fun.main/1-">)
    (simple_script 0.1.0) lib/bakeware/script.ex:36: SimpleScript._main/0
    (elixir 1.11.1) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &SimpleScript._main/0
    Args: []

```

**Comment by fhunleth** [comment]
Thanks for reporting this. We should have a fix tomorrow or Friday. In the mean time, a workaround is to either work off the SpawnFest repository at https://github.com/spawnfest/bakeware or to edit the sample's `mix.exs` to remove `runtime: false` on the `:bakeware` dependency.

**Comment by suprafly** [comment]
I actually just did a quick PR for a fix. Turns out to be simple :+1:

**Comment by suprafly** [comment]
Btw, love this project. Happy to help out however I can.
